-- Studio-Masons ERP — Design brief template seed (imported from the office
-- questionnaires). Run AFTER 0006_design_department.sql. Idempotent: re-running
-- is a no-op once each template already has a published v1. Edit further in the
-- in-app template editor (which publishes new versions).

do $$
declare v_tpl uuid; v_ver uuid; v_sec uuid;
begin
  insert into public.design_templates (key,label,discipline) values ('interior_commercial','Interior Design — Commercial Fitout','interior') on conflict (key) do nothing;
  select id into v_tpl from public.design_templates where key='interior_commercial';
  if not exists (select 1 from public.design_template_versions where template_id=v_tpl) then
    insert into public.design_template_versions (template_id,version_no,status) values (v_tpl,1,'published') returning id into v_ver;
    insert into public.design_template_columns (version_id,sort,key,label,kind) values (v_ver,0,'yes_no','Yes / No','yes_no'),(v_ver,1,'response','Response','longtext'),(v_ver,2,'remarks','Remarks','text');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,0,'Basic project brief') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'What is the total area available for the office?'),(v_sec,1,'Is this a new office, expansion, or renovation of an existing space?'),(v_sec,2,'What is the expected headcount on day one?'),(v_sec,3,'What is the future headcount growth to be considered?'),(v_sec,4,'What is the expected project timeline and handover date?'),(v_sec,5,'Is the office intended mainly for internal teams, client visits, or both?'),(v_sec,6,'Should the space have a premium client-facing character or a more functional engineering-office approach?');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,1,'Team and seating requirement') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'How many total workstations are required?'),(v_sec,1,'How many fixed seats and how many flexible/hot desks are required?'),(v_sec,2,'What are the different teams using the space?'),(v_sec,3,'Should specific teams sit close to the lab?'),(v_sec,4,'Are there any teams requiring restricted or confidential seating areas?'),(v_sec,5,'Are manager cabins required or should managers sit in open workstations?'),(v_sec,6,'How many cabins are required?'),(v_sec,7,'Do any leadership cabins require discussion seating inside?');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,2,'Meeting and collaboration spaces') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'How many meeting rooms are required?'),(v_sec,1,'What capacities are needed?'),(v_sec,2,'Is a client demo room required?'),(v_sec,3,'Should the demo room be separate from the meeting rooms?'),(v_sec,4,'Are VC-enabled rooms required?'),(v_sec,5,'What AV setup is expected?'),(v_sec,6,'Are phone booths or focus rooms required?'),(v_sec,7,'Is a war room/project room required for technical discussions?'),(v_sec,8,'Are writable walls or smart boards required?');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,3,'Lab requirement') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'What is the exact function of the lab?'),(v_sec,1,'Hardware testing?'),(v_sec,2,'Video streaming testing?'),(v_sec,3,'Set-top box testing?'),(v_sec,4,'Network testing?'),(v_sec,5,'Software QA?'),(v_sec,6,'Demo setup?'),(v_sec,7,'How many people will work inside the lab at one time?'),(v_sec,8,'How many lab benches are required?'),(v_sec,9,'What equipment will be used in the lab?'),(v_sec,10,'Will there be server racks or network racks?'),(v_sec,11,'How many racks are required and what size?'),(v_sec,12,'Will the rack be inside the lab or in a separate IT/server room?'),(v_sec,13,'Are multiple screens required for video testing?'),(v_sec,14,'What is the quantity and size of screens/monitors required?'),(v_sec,15,'Are test devices like STBs, routers, encoders, decoders, media players, or storage devices used?'),(v_sec,16,'Is the equipment heat-generating?'),(v_sec,17,'Is 24/7 cooling required for the lab or rack area?'),(v_sec,18,'Is UPS backup required for the lab?'),(v_sec,19,'Should the lab be access-controlled?'),(v_sec,20,'Is acoustic separation required between the lab and workstations?'),(v_sec,21,'Is ESD flooring or anti-static workbench required?'),(v_sec,22,'Is lockable equipment storage required inside the lab?'),(v_sec,23,'Are any items confidential or client-owned?');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,4,'IT, data and power') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'What is the IT infrastructure requirement?'),(v_sec,1,'How many data points are required per workstation?'),(v_sec,2,'How many data points are required per lab bench?'),(v_sec,3,'Is separate network zoning required for office and lab?'),(v_sec,4,'Is a dedicated server/IT room required?'),(v_sec,5,'Is UPS required for workstations, lab, server, or only critical equipment?'),(v_sec,6,'What is the required UPS backup duration?'),(v_sec,7,'Are floor boxes required or can power/data come from walls or ceiling?'),(v_sec,8,'Are under-desk cable trays required?'),(v_sec,9,'Is Wi-Fi-only working acceptable in any areas?'),(v_sec,10,'Are there any special earthing requirements for lab equipment?'),(v_sec,11,'Who will provide active IT equipment: client or contractor?');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,5,'Security and access control') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'What areas need access control?'),(v_sec,1,'Main entry'),(v_sec,2,'Lab'),(v_sec,3,'Server/IT room'),(v_sec,4,'Store'),(v_sec,5,'Leadership area'),(v_sec,6,'Is visitor access allowed inside the lab?'),(v_sec,7,'Should the client demo room be accessible without entering the main office?'),(v_sec,8,'Is CCTV required?'),(v_sec,9,'Is a visitor management system required?'),(v_sec,10,'Are there NDA/confidentiality restrictions for the lab or demo area?'),(v_sec,11,'Is there any requirement for secure storage of devices or client hardware?');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,6,'Reception and branding') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Is a reception required?'),(v_sec,1,'Should the reception be formal or minimal?'),(v_sec,2,'Is a waiting lounge required?'),(v_sec,3,'How many visitors should it accommodate?'),(v_sec,4,'Should the reception include a digital screen/media wall?'),(v_sec,5,'Are brand guidelines available?'),(v_sec,6,'What are the approved brand colors, fonts, and logo usage rules?'),(v_sec,7,'Are environmental graphics required?'),(v_sec,8,'Should the design reflect video streaming, broadcast, cloud, AI, or cybersecurity themes?'),(v_sec,9,'Are there any global Synamedia office references to follow?');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,7,'Pantry and support spaces') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Is a pantry required?'),(v_sec,1,'Should it be dry pantry or full-service pantry?'),(v_sec,2,'How many people should the pantry serve?'),(v_sec,3,'Is a cafeteria seating area required?'),(v_sec,4,'Is a coffee point required near work areas?'),(v_sec,5,'Are refrigerator, microwave, dishwasher, vending machine, or coffee machine required?'),(v_sec,6,'Are lockers required?'),(v_sec,7,'Is a print/copy area required?'),(v_sec,8,'Is a stationery/store room required?'),(v_sec,9,'Is a housekeeping/store room required?'),(v_sec,10,'Is a mother’s room, wellness room, or first-aid room required?');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,8,'Furniture requirements') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'What workstation size is preferred?'),(v_sec,1,'Are height-adjustable desks required?'),(v_sec,2,'Are dual monitor arms required?'),(v_sec,3,'Is pedestal storage required for each user?'),(v_sec,4,'Are lockers preferred instead of pedestals?'),(v_sec,5,'What type of lab workbench is required?'),(v_sec,6,'Should lab benches have overhead shelves?'),(v_sec,7,'Should lab benches have integrated power strips?'),(v_sec,8,'Is lockable storage required below lab benches?'),(v_sec,9,'Are ergonomic chairs required for all users?'),(v_sec,10,'Any preferred furniture brand or standard?');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,9,'MEP and technical coordination') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'What is the required HVAC operating schedule?'),(v_sec,1,'Will the lab operate after office hours?'),(v_sec,2,'Are there any rooms requiring 24/7 AC?'),(v_sec,3,'Is additional cooling needed for rack/server areas?'),(v_sec,4,'Are there any special exhaust requirements?'),(v_sec,5,'What is the expected lighting lux level for office and lab?'),(v_sec,6,'Should lighting be dimmable in demo/meeting rooms?'),(v_sec,7,'Is emergency lighting required as per building norms?'),(v_sec,8,'Are smoke detectors, sprinklers, fire alarms, and extinguishers already available?'),(v_sec,9,'Are any modifications to fire systems allowed by the building?'),(v_sec,10,'Are there landlord restrictions for core cutting, slab drilling, ceiling suspension, or AC changes?');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,10,'Acoustic requirement') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Are meeting rooms to be acoustically treated?'),(v_sec,1,'Is sound privacy required for client calls?'),(v_sec,2,'Should the lab be acoustically isolated from the open office?'),(v_sec,3,'Are phone booths required for regular calls?'),(v_sec,4,'Is acoustic ceiling required in open office?'),(v_sec,5,'Are acoustic panels or fabric wall panels acceptable aesthetically?'),(v_sec,6,'Should the demo room have enhanced acoustic treatment?');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,11,'Compliance and building constraints') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'What are the building guidelines?'),(v_sec,1,'Are as-built drawings available?'),(v_sec,2,'Are fire escape routes and door widths already approved?'),(v_sec,3,'Are there restrictions on ceiling height?'),(v_sec,4,'Are there floor loading restrictions, especially for lab racks or UPS?'),(v_sec,5,'Are landlord approvals required for MEP modifications?'),(v_sec,6,'Is there a specific vendor approval process?'),(v_sec,7,'Are working-hour restrictions applicable for site execution?');
  end if;
end $$;

do $$
declare v_tpl uuid; v_ver uuid; v_sec uuid;
begin
  insert into public.design_templates (key,label,discipline) values ('mep_office','MEP — Office Fitout','mep') on conflict (key) do nothing;
  select id into v_tpl from public.design_templates where key='mep_office';
  if not exists (select 1 from public.design_template_versions where template_id=v_tpl) then
    insert into public.design_template_versions (template_id,version_no,status) values (v_tpl,1,'published') returning id into v_ver;
    insert into public.design_template_columns (version_id,sort,key,label,kind) values (v_ver,0,'option_1','Option-1','text'),(v_ver,1,'option_2','Option-2','text'),(v_ver,2,'consultant_rec','Consultant''s Recommendation','longtext'),(v_ver,3,'client_response','Client Response','longtext'),(v_ver,4,'remarks','Remarks','text');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,0,'HVAC - INSIDE DESIGN CONDITIONS') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Inside Design Temperature - Office Workstation areas'),(v_sec,1,'Inside Design Temperature - Meeting Rooms'),(v_sec,2,'Inside Design Temperature - UPS Rooms'),(v_sec,3,'Inside Design Temperature - Battery Rooms'),(v_sec,4,'Inside Design Temperature - Server Room/ MDF/ IDF / Hub Rooms'),(v_sec,5,'Inside Design Temperature - Lab (if any)'),(v_sec,6,'Relative Humidity- Office Workstation areas & Meeting Rooms'),(v_sec,7,'Relative Humidity - Server Room/ MDF/ IDF / Hub Rooms'),(v_sec,8,'Relative Humidity-UPS & Baterry rooms');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,1,'HVAC - GREEN CERTIFICATION') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Type');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,2,'HVAC - OUTDOOR AIR REQUIREMENTS- FRESH AIR FOR AHU') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Office Spaces');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,3,'HVAC - CRITICAL ROOM REQUIREMENTS') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'IDF & MDF Room ( Server Rooms)'),(v_sec,1,'UPS & Battery Room'),(v_sec,2,'Battery Room Hydrogen Release Exhaust');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,4,'HVAC - AHU FILTRATION LEVELS') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Filtration');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,5,'HVAC - OFFICE AREA AIR DISTRIBUTION') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Duct works'),(v_sec,1,'Varaiable Frequency drives (VFD''s) for AHU''s & VAV boxes');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,6,'HVAC - CAFETERIA/ DINING SPACE') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Cafetria AC Requirements');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,7,'HVAC - TOILETS') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Number of Air changes per hour');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,8,'HVAC - ELECTRICAL ROOM') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Number of Air changes per hour');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,9,'HVAC - PANTRY/ MICRO KITCHEN') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Number of Air changes per hour');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,10,'HVAC - STORAGE ROOM REQUIREMENTS') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Storage Rooms');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,11,'ELECTRICAL & ELV - Lighting Requirements') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'M & E Rooms (Electrical,UPS, IDF/MDF Room/ Server Room, etc.)'),(v_sec,1,'Workstation/Open Office'),(v_sec,2,'Cabins'),(v_sec,3,'Discussion Room'),(v_sec,4,'Conference room (Small,Medium,Large)'),(v_sec,5,'Collab Space ,Corridors and Passage'),(v_sec,6,'Reception'),(v_sec,7,'Occupancy sensors/ Motion sensors'),(v_sec,8,'Extent of Emergency lighting on UPS/inverter'),(v_sec,9,'Emergency lighting and Battery backup'),(v_sec,10,'Lighting Control - Workstation'),(v_sec,11,'Lighting Control - Cabins'),(v_sec,12,'Lighting Control - Conference rooms (Small,Medium,Large)'),(v_sec,13,'Lighting Control - Reception/Cafeteria /Pantry /Electrical room/IT Room'),(v_sec,14,'Any other specific requirements');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,12,'ELECTRICAL & ELV - Power Socket requirements') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Power for worksation'),(v_sec,1,'Power requirement for each Work station'),(v_sec,2,'No. of Monitors per Work station'),(v_sec,3,'No. of sockets in each Work Station (UPS)'),(v_sec,4,'No. of sockets in each Work Station (RP)'),(v_sec,5,'No. of sockets in each Cabin(UPS)'),(v_sec,6,'No. of sockets in each Cabin(RP)'),(v_sec,7,'No. of Power sockets in meeting/conference room'),(v_sec,8,'Switch Control for Workstation sockets.'),(v_sec,9,'Socket location'),(v_sec,10,'Socket Type'),(v_sec,11,'Any other specific requirements'),(v_sec,12,'Type of raceways - Ceiling with cover'),(v_sec,13,'Type of raceways - Floor'),(v_sec,14,'Type of Cable trays (Ladder)'),(v_sec,15,'Type of Cable trays (Perforated)'),(v_sec,16,'Power and IT Cable routing'),(v_sec,17,'Cables for power Sockets (RP/UPS)'),(v_sec,18,'Type of Conduit');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,13,'ELECTRICAL & ELV - NETWORKING') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'No. of Data points per workstation'),(v_sec,1,'No. of Redundant Data points per workstation'),(v_sec,2,'Voice connectivity to the workstation'),(v_sec,3,'No. of Voice points per workstation'),(v_sec,4,'Wi - Fi (Wireless internet)'),(v_sec,5,'Type of cable (Data and Voice)'),(v_sec,6,'Type of cable (Wif)'),(v_sec,7,'Any other specific requirements');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,14,'ELECTRICAL & ELV - SECURITY SERVICES') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Access Control'),(v_sec,1,'Access Control is by'),(v_sec,2,'Attendance Management'),(v_sec,3,'Surveillance by using CCTV'),(v_sec,4,'Type of cameras'),(v_sec,5,'Storgae Capcity'),(v_sec,6,'Any other specific requirements');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,15,'ELECTRICAL & ELV - SECURITY SERVICES') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Workstation UPS'),(v_sec,1,'Back up Time'),(v_sec,2,'IDF/MDF UPS'),(v_sec,3,'Back up Time'),(v_sec,4,'IDF/MDF UPS - Redundancy'),(v_sec,5,'No of Racks'),(v_sec,6,'Load per rack in KVA (IDF/MDF)');
    insert into public.design_template_sections (version_id,sort,title) values (v_ver,16,'PHE & FIRE - General') returning id into v_sec;
    insert into public.design_template_questions (section_id,sort,text) values (v_sec,0,'Please confirm entire floor is with false ceiling or open type ceiling.'),(v_sec,1,'Whether there will be false floor of 150mm to run raceways or only screed will be available'),(v_sec,2,'Please confirm Fire alarm System - Dedicated addressable FA panel required for office Floor'),(v_sec,3,'Public addaress system - Dedicated PA panel with mixer & pre amplifier, console will be considered for office floor'),(v_sec,4,'Fire alarm system will be planned and further integrated with base builder panel Smoke/Heat detectors.'),(v_sec,5,'PA system will be planned with ceiling mounted speakers/wallmounted speakers and further integration with base builder panel with as required.'),(v_sec,6,'Please confirm IDF / MDF/ Server rooms sprinkler required or any gas suppression system required (Modullar type clean agent fire extinguishers or any other).'),(v_sec,7,'Please confirm IDF / MDF/ Server rooms requirements of Water Leak Detection and Rodent Repellant system.'),(v_sec,8,'Please confirm UPS & Battery room any gas suppression required or only fire extinguishers required.'),(v_sec,9,'Extinguishers - ABC/ C02/ type will be planned entire floors or Clean agent system to be proposed . Client to specify'),(v_sec,10,'Signages will be planned in accordance with exit passage - Biderectional LED Powered signages will be considered.'),(v_sec,11,'Sprinkler system - We anticipate Upright sprinklers provided by builder and pendant/concealed type sprinklers with flexible hose will be provided in the false ceiling areas based on ceiling height.'),(v_sec,12,'Plumbing Requirements for in Office area -Mothers Room-Domestic Water/ Drainage System/ Hot water/ RO Water');
  end if;
end $$;
